name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Set up Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build static status page
      run: cd status-web && yarn && yarn build && cd ../

    - name: Get dependencies
      run: go mod download && go install github.com/rakyll/statik

    - name: Static->GO generation
      run: cd cmd/server && statik --src=../../status-web/build/ && cd ../../

    - name: Build
      run: go build -v .
